apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  namespace: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
        - name: backend
          image: prathamvish333/notes-backend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: notes-db-secret
                  key: database-url
