apiVersion: v1
kind: Service
metadata:
  name: notes-backend-service
  namespace: notes-app
spec:
  type: LoadBalancer
  selector:
    app: notes-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
