apiVersion: v1
kind: Service
metadata:
  name: notes-frontend-service
  namespace: notes-app
spec:
  type: LoadBalancer
  selector:
    app: notes-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
