apiVersion: v1
kind: Secret
metadata:
  name: notes-db-secret
  namespace: notes-app
type: Opaque
stringData:
  postgres-user: "admin"
  postgres-password: "password123"
  postgres-db: "notesdb"
  database-url: "postgresql://admin:password123@notes-db:5432/notesdb"
